Description: CloudFormation Deployment for reading/writing to Iceberg tables from Snowflake via. Polaris and reading via. GDC catalog federation
Parameters:
  PolarisCatalogIAMRole:
    Type: String
    Description: IAM user ARN from the Polaris catalog
    
  PolarisCatalogExternalId:
    Type: String
    Description: External Id from the POlaris catalog

  StorageIAMRole:
    Type: String
    Description: STORAGE_AWS_IAM_USER_ARN from the external volume
    
  StorageExternalId:
    Type: String
    Description: STORAGE_AWS_IAM_USER_ARN from the external volume
    
Resources:
  #
  # S3 Bucket
  #
  S3:
    Type: AWS::S3::Bucket
  
  #
  # Snowflake Polaris Catalog IAM Role
  # 
  SnowflakePolarisCatalogIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref PolarisCatalogIAMRole
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref PolarisCatalogExternalId
      Policies:
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  
  #
  # Snowflake External Volume Storage IAM Role
  #
  SnowflakePolarisStorageIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref StorageIAMRole
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref StorageExternalId
      Policies:
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

Outputs:
  SnowflakePolarisCatalogIAMRole:
    Description: Use this for s3 role ARN when creating the catalog in Polaris
    Value: !GetAtt SnowflakePolarisCatalogIAMRole.Arn

  SnowflakePolarisStorageIAMRole:
    Description: STORAGE_AWS_ROLE_ARN when creating the external volume
    Value: !GetAtt SnowflakePolarisStorageIAMRole.Arn

  StorageBaseUri:
    Description: Use this default base location when creating the catalog in Polaris and STORAGE_BASE_URL when creating the external volume
    Value: !Join 
      - ''
      - - 's3://'
        - !Ref S3
