Description: CloudFormation Deployment for reading/writing to Iceberg tables from Snowflake via. Polaris and reading via. GDC catalog federation
Resources:
  #
  # S3 Bucket
  #
  S3:
    Type: AWS::S3::Bucket
  
  #
  # Snowflake IAM Role
  # 
  SnowflakePolarisIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::535002871755:root" # replace with 
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - '*'
                Resource: '*'

Outputs:
  SnowflakePolarisIAMRoleArn:
    Description: Use this for s3 role ARN when creating the catalog in Polaris
    Value: !GetAtt SnowflakePolarisIAMRole.Arn

  StorageBaseUri:
    Description: Use this default base location when creating the catalog in Polaris
    Value: !Join 
      - ''
      - - 's3://'
        - !Ref S3
        - '/iceberg/'
